# Generated by Django 6.0.3 on 2026-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='admin_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
