# Generated by Django 6.0.3 on 2026-03-10 17:58

from decimal import Decimal
from django.db import migrations, models


def backfill_status_and_fine(apps, schema_editor):
    """
    Set status='returned' + calculate fine_amount for historically returned records.
    Active (unreturned) records keep the default status='borrowing' and fine_amount=0.
    """
    BorrowRecord = apps.get_model('librarian', 'BorrowRecord')
    to_update = []
    for record in BorrowRecord.objects.filter(return_date__isnull=False):
        record.status = 'returned'
        if record.return_date > record.due_date:
            overdue_days = (record.return_date - record.due_date).days
            record.fine_amount = Decimal(overdue_days * 10)
        to_update.append(record)
    BorrowRecord.objects.bulk_update(to_update, ['status', 'fine_amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_adminprofile_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='created_by_admin',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('borrowing', 'Borrowing'), ('returned', 'Returned')], default='borrowing', max_length=20),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(backfill_status_and_fine, migrations.RunPython.noop),
    ]
